### ISSUE TITLE
Uncaught error

### ISSUE THREAD

**Issue by adrianmihalko** [martin-honnen/XSLT-Tester#1]
Hi Martin,

I can run the application, but If I type something in the XSLT window the application is crashing:

```
[info] Loading global plugins from /home/madrian/.sbt/0.13/plugins
[info] Loading project definition from /home/madrian/scripts/XSLTester/project
[info] Set current project to test (in build file:/home/madrian/scripts/XSLTester/)

--- (Running the application from SBT, auto-reloading is enabled) ---

[info] play - Listening for HTTP on /0.0.0.0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

[info] play - database [default] connected at jdbc:mysql://localhost/fiddles
[info] play - Application started (Dev)
Uncaught error from thread [play-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[play]
java.lang.ExceptionInInitializerError
        at net.sf.saxon.regex.RECompiler.escape(RECompiler.java:366)
        at net.sf.saxon.regex.RECompiler.parseTerminal(RECompiler.java:930)
        at net.sf.saxon.regex.RECompiler.piece(RECompiler.java:971)
        at net.sf.saxon.regex.RECompiler.parseBranch(RECompiler.java:1091)
        at net.sf.saxon.regex.RECompiler.parseExpr(RECompiler.java:1141)
        at net.sf.saxon.regex.RECompiler.compile(RECompiler.java:1273)
        at net.sf.saxon.regex.ARegularExpression.<init>(ARegularExpression.java:50)
        at net.sf.saxon.java.JavaPlatform.compileRegularExpression(JavaPlatform.java:326)
        at net.sf.saxon.functions.RegexFunction.tryToBindRegularExpression(RegexFunction.java:48)
        at net.sf.saxon.functions.RegexFunction.makeFunctionCall(RegexFunction.java:86)
        at net.sf.saxon.functions.Replace.makeFunctionCall(Replace.java:51)
        at net.sf.saxon.functions.RegexFunctionSansFlags.makeFunctionCall(RegexFunctionSansFlags.java:47)
        at net.sf.saxon.functions.registry.BuiltInFunctionSet.bind(BuiltInFunctionSet.java:188)
        at net.sf.saxon.functions.FunctionLibraryList.bind(FunctionLibraryList.java:105)
        at net.sf.saxon.expr.parser.XPathParser.parseFunctionCall(XPathParser.java:3189)
        at net.sf.saxon.expr.parser.XPathParser.parseBasicStep(XPathParser.java:2076)
        at net.sf.saxon.expr.parser.XPathParser.parseStepExpression(XPathParser.java:1957)
        at net.sf.saxon.expr.parser.XPathParser.parseRelativePath(XPathParser.java:1882)
        at net.sf.saxon.expr.parser.XPathParser.parsePathExpression(XPathParser.java:1844)
        at net.sf.saxon.expr.parser.XPathParser.parseSimpleMappingExpression(XPathParser.java:1858)
        at net.sf.saxon.expr.parser.XPathParser.parseUnaryExpression(XPathParser.java:1713)
        at net.sf.saxon.expr.parser.XPathParser.parseExprSingle(XPathParser.java:660)
        at net.sf.saxon.expr.parser.XPathParser.parseFunctionArgument(XPathParser.java:3390)
        at net.sf.saxon.expr.parser.XPathParser.parseFunctionCall(XPathParser.java:3155)
        at net.sf.saxon.expr.parser.XPathParser.parseBasicStep(XPathParser.java:2076)
        at net.sf.saxon.expr.parser.XPathParser.parseStepExpression(XPathParser.java:1957)
        at net.sf.saxon.expr.parser.XPathParser.parseRelativePath(XPathParser.java:1882)
        at net.sf.saxon.expr.parser.XPathParser.parsePathExpression(XPathParser.java:1844)
        at net.sf.saxon.expr.parser.XPathParser.parseSimpleMappingExpression(XPathParser.java:1858)
        at net.sf.saxon.expr.parser.XPathParser.parseUnaryExpression(XPathParser.java:1713)
        at net.sf.saxon.expr.parser.XPathParser.parseExprSingle(XPathParser.java:660)
        at net.sf.saxon.expr.parser.XPathParser.parseFunctionArgument(XPathParser.java:3390)
        at net.sf.saxon.expr.parser.XPathParser.parseFunctionCall(XPathParser.java:3155)
        at net.sf.saxon.expr.parser.XPathParser.parseBasicStep(XPathParser.java:2076)
        at net.sf.saxon.expr.parser.XPathParser.parseStepExpression(XPathParser.java:1957)
[ERROR] [01/29/2018 18:40:44.406] [play-akka.actor.default-dispatcher-3] [ActorSystem(play)] Uncaught error from thread [play-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.ExceptionInInitializerError
        at net.sf.saxon.regex.RECompiler.escape(RECompiler.java:366)
        at net.sf.saxon.regex.RECompiler.parseTerminal(RECompiler.java:930)
        at net.sf.saxon.regex.RECompiler.piece(RECompiler.java:971)
        at net.sf.saxon.regex.RECompiler.parseBranch(RECompiler.java:1091)
        at net.sf.saxon.regex.RECompiler.parseExpr(RECompiler.java:1141)
        at net.sf.saxon.regex.RECompiler.compile(RECompiler.java:1273)
        at net.sf.saxon.regex.ARegularExpression.<init>(ARegularExpression.java:50)
        at net.sf.saxon.java.JavaPlatform.compileRegularExpression(JavaPlatform.java:326)
        at net.sf.saxon.functions.RegexFunction.tryToBindRegularExpression(RegexFunction.java:48)
        at net.sf.saxon.functions.RegexFunction.makeFunctionCall(RegexFunction.java:86)
        at net.sf.saxon.functions.Replace.makeFunctionCall(Replace.java:51)
        at net.sf.saxon.functions.RegexFunctionSansFlags.makeFunctionCall(RegexFunctionSansFlags.java:47)
        at net.sf.saxon.functions.registry.BuiltInFunctionSet.bind(BuiltInFunctionSet.java:188)
        at net.sf.saxon.functions.FunctionLibraryList.bind(FunctionLibraryList.java:105)
        at net.sf.saxon.expr.parser.XPathParser.parseFunctionCall(XPathParser.java:3189)
        at net.sf.saxon.expr.parser.XPathParser.parseBasicStep(XPathParser.java:2076)
        at net.sf.saxon.expr.parser.XPathParser.parseStepExpression(XPathParser.java:1957)
        at net.sf.saxon.expr.parser.XPathParser.parseRelativePath(XPathParser.java:1882)
        at net.sf.saxon.expr.parser.XPathParser.parsePathExpression(XPathParser.java:1844)
        at net.sf.saxon.expr.parser.XPathParser.parseSimpleMappingExpression(XPathParser.java:1858)
        at net.sf.saxon.expr.parser.XPathParser.parseUnaryExpression(XPathParser.java:1713)
        at net.sf.saxon.expr.parser.XPathParser.parseExprSingle(XPathParser.java:660)
        at net.sf.saxon.expr.parser.XPathParser.parseFunctionArgument(XPathParser.java:3390)
        at net.sf.saxon.expr.parser.XPathParser.parseFunctionCall(XPathParser.java:3155)
        at net.sf.saxon.expr.parser.XPathParser.parseBasicStep(XPathParser.java:2076)
        at net.sf.saxon.expr.parser.XPathParser.parseStepExpression(XPathParser.java:1957)
        at net.sf.saxon.expr.parser.XPathParser.parseRelativePath(XPathParser.java:1882)
        at net.sf.saxon.expr.parser.XPathParser.parsePathExpression(XPathParser.java:1844)
        at net.sf.saxon.expr.parser.XPathParser.parseSimpleMappingExpression(XPathParser.java:1858)
        at net.sf.saxon.expr.parser.XPathParser.parseUnaryExpression(XPathParser.java:1713)
        at net.sf.saxon.expr.parser.XPathParser.parseExprSingle(XPathParser.java:660)
        at net.sf.saxon.expr.parser.XPathParser.parseFunctionArgument(XPathParser.java:3390)
        at net.sf.saxon.expr.parser.XPathParser.parseFunctionCall(XPathParser.java:3155)
        at net.sf.saxon.expr.parser.XPathParser.parseBasicStep(XPathParser.java:2076)
        at net.sf.saxon.expr.parser.XPathParser.parseStepExpression(XPathParser.java:1957)
        at net.sf.saxon.expr.parser.XPathParser.parseRelativePath(XPathParser.java:1882)
        at net.sf.saxon.expr.parser.XPathParser.parsePathExpression(XPathParser.java:1844)
        at net.sf.saxon.expr.parser.XPathParser.parseSimpleMappingExpression(XPathParser.java:1858)
        at net.sf.saxon.expr.parser.XPathParser.parseUnaryExpression(XPathParser.java:1713)
        at net.sf.saxon.expr.parser.XPathParser.parseExprSingle(XPathParser.java:660)
        at net.sf.saxon.expr.parser.XPathParser.parseFunctionArgument(XPathParser.java:3390)
        at net.sf.saxon.expr.parser.XPathParser.parseFunctionCall(XPathParser.java:3155)
        at net.sf.saxon.expr.parser.XPathParser.parseBasicStep(XPathParser.java:2076)
        at net.sf.saxon.expr.parser.XPathParser.parseStepExpression(XPathParser.java:1957)
        at net.sf.saxon.expr.parser.XPathParser.parseRelativePath(XPathParser.java:1882)
        at net.sf.saxon.expr.parser.XPathParser.parsePathExpression(XPathParser.java:1844)
        at net.sf.saxon.expr.parser.XPathParser.parseSimpleMappingExpression(XPathParser.java:1858)
        at net.sf.saxon.expr.parser.XPathParser.parseUnaryExpression(XPathParser.java:1713)
        at net.sf.saxon.expr.parser.XPathParser.parseExprSingle(XPathParser.java:660)
        at net.sf.saxon.expr.parser.XPathParser.parseFunctionArgument(XPathParser.java:3390)
        at net.sf.saxon.expr.parser.XPathParser.parseFunctionCall(XPathParser.java:3155)
        at net.sf.saxon.expr.parser.XPathParser.parseBasicStep(XPathParser.java:2076)
        at net.sf.saxon.expr.parser.XPathParser.parseStepExpression(XPathParser.java:1957)
        at net.sf.saxon.expr.parser.XPathParser.parseRelativePath(XPathParser.java:1882)
        at net.sf.saxon.expr.parser.XPathParser.parsePathExpression(XPathParser.java:1844)
        at net.sf.saxon.expr.parser.XPathParser.parseSimpleMappingExpression(XPathParser.java:1858)
        at net.sf.saxon.expr.parser.XPathParser.parseUnaryExpression(XPathParser.java:1713)
        at net.sf.saxon.expr.parser.XPathParser.parseExprSingle(XPathParser.java:660)
        at net.sf.saxon.expr.parser.XPathParser.parseExpression(XPathParser.java:595)
        at net.sf.saxon.expr.parser.XPathParser.parse(XPathParser.java:466)
        at net.sf.saxon.expr.parser.ExpressionTool.make(ExpressionTool.java:105)
        at net.sf.saxon.style.StyleElement.makeExpression(StyleElement.java:760)
        at net.sf.saxon.style.XSLValueOf.prepareAttributes(XSLValueOf.java:51)
        at net.sf.saxon.style.StyleElement.processAttributes(StyleElement.java:634)
        at net.sf.saxon.style.StyleElement.processAllAttributes(StyleElement.java:579)
        at net.sf.saxon.style.StyleElement.processAllAttributes(StyleElement.java:584)
        at net.sf.saxon.style.StyleElement.processAllAttributes(StyleElement.java:584)
        at net.sf.saxon.style.XSLTemplate.processAllAttributes(XSLTemplate.java:397)
        at net.sf.saxon.style.PrincipalStylesheetModule.processAllAttributes(PrincipalStylesheetModule.java:607)
        at net.sf.saxon.style.PrincipalStylesheetModule.preprocess(PrincipalStylesheetModule.java:384)
        at net.sf.saxon.style.Compilation.compilePackage(Compilation.java:288)
        at net.sf.saxon.style.StylesheetModule.loadStylesheet(StylesheetModule.java:258)
        at net.sf.saxon.style.Compilation.compileSingletonPackage(Compilation.java:106)
        at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:739)
        at net.sf.saxon.jaxp.SaxonTransformerFactory.newTemplates(SaxonTransformerFactory.java:155)
        at net.sf.saxon.jaxp.SaxonTransformerFactory.newTransformer(SaxonTransformerFactory.java:111)
        at net.xsltransform.plugin.Saxon9HEPlugin.newTransformer(Saxon9HEPlugin.java:115)
        at controllers.Application.transform(Application.java:105)
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$2$$anonfun$apply$2.apply(routes_routing.scala:109)
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$2$$anonfun$apply$2.apply(routes_routing.scala:109)
        at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183)
        at play.core.Router$Routes$$anon$1.invocation(Router.scala:377)
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56)
        at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91)
        at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90)
        at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)
        at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: Unable to read categories.xml file
        at net.sf.saxon.regex.charclass.Categories.build(Categories.java:116)
        at net.sf.saxon.regex.charclass.Categories.getCategory(Categories.java:206)
        at net.sf.saxon.regex.charclass.Categories.<clinit>(Categories.java:180)
        ... 97 more

        at net.sf.saxon.expr.parser.XPathParser.parseRelativePath(XPathParser.java:1882)
        at net.sf.saxon.expr.parser.XPathParser.parsePathExpression(XPathParser.java:1844)
        at net.sf.saxon.expr.parser.XPathParser.parseSimpleMappingExpression(XPathParser.java:1858)
        at net.sf.saxon.expr.parser.XPathParser.parseUnaryExpression(XPathParser.java:1713)
        at net.sf.saxon.expr.parser.XPathParser.parseExprSingle(XPathParser.java:660)
        at net.sf.saxon.expr.parser.XPathParser.parseFunctionArgument(XPathParser.java:3390)
        at net.sf.saxon.expr.parser.XPathParser.parseFunctionCall(XPathParser.java:3155)
        at net.sf.saxon.expr.parser.XPathParser.parseBasicStep(XPathParser.java:2076)
        at net.sf.saxon.expr.parser.XPathParser.parseStepExpression(XPathParser.java:1957)
        at net.sf.saxon.expr.parser.XPathParser.parseRelativePath(XPathParser.java:1882)
        at net.sf.saxon.expr.parser.XPathParser.parsePathExpression(XPathParser.java:1844)
        at net.sf.saxon.expr.parser.XPathParser.parseSimpleMappingExpression(XPathParser.java:1858)
        at net.sf.saxon.expr.parser.XPathParser.parseUnaryExpression(XPathParser.java:1713)
        at net.sf.saxon.expr.parser.XPathParser.parseExprSingle(XPathParser.java:660)
        at net.sf.saxon.expr.parser.XPathParser.parseFunctionArgument(XPathParser.java:3390)
        at net.sf.saxon.expr.parser.XPathParser.parseFunctionCall(XPathParser.java:3155)
        at net.sf.saxon.expr.parser.XPathParser.parseBasicStep(XPathParser.java:2076)
        at net.sf.saxon.expr.parser.XPathParser.parseStepExpression(XPathParser.java:1957)
        at net.sf.saxon.expr.parser.XPathParser.parseRelativePath(XPathParser.java:1882)
        at net.sf.saxon.expr.parser.XPathParser.parsePathExpression(XPathParser.java:1844)
        at net.sf.saxon.expr.parser.XPathParser.parseSimpleMappingExpression(XPathParser.java:1858)
        at net.sf.saxon.expr.parser.XPathParser.parseUnaryExpression(XPathParser.java:1713)
        at net.sf.saxon.expr.parser.XPathParser.parseExprSingle(XPathParser.java:660)
        at net.sf.saxon.expr.parser.XPathParser.parseExpression(XPathParser.java:595)
        at net.sf.saxon.expr.parser.XPathParser.parse(XPathParser.java:466)
        at net.sf.saxon.expr.parser.ExpressionTool.make(ExpressionTool.java:105)
        at net.sf.saxon.style.StyleElement.makeExpression(StyleElement.java:760)
        at net.sf.saxon.style.XSLValueOf.prepareAttributes(XSLValueOf.java:51)
        at net.sf.saxon.style.StyleElement.processAttributes(StyleElement.java:634)
        at net.sf.saxon.style.StyleElement.processAllAttributes(StyleElement.java:579)
        at net.sf.saxon.style.StyleElement.processAllAttributes(StyleElement.java:584)
        at net.sf.saxon.style.StyleElement.processAllAttributes(StyleElement.java:584)
        at net.sf.saxon.style.XSLTemplate.processAllAttributes(XSLTemplate.java:397)
        at net.sf.saxon.style.PrincipalStylesheetModule.processAllAttributes(PrincipalStylesheetModule.java:607)
        at net.sf.saxon.style.PrincipalStylesheetModule.preprocess(PrincipalStylesheetModule.java:384)
        at net.sf.saxon.style.Compilation.compilePackage(Compilation.java:288)
        at net.sf.saxon.style.StylesheetModule.loadStylesheet(StylesheetModule.java:258)
        at net.sf.saxon.style.Compilation.compileSingletonPackage(Compilation.java:106)
        at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:739)
        at net.sf.saxon.jaxp.SaxonTransformerFactory.newTemplates(SaxonTransformerFactory.java:155)
        at net.sf.saxon.jaxp.SaxonTransformerFactory.newTransformer(SaxonTransformerFactory.java:111)
        at net.xsltransform.plugin.Saxon9HEPlugin.newTransformer(Saxon9HEPlugin.java:115)
        at controllers.Application.transform(Application.java:105)
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$2$$anonfun$apply$2.apply(routes_routing.scala:109)
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$2$$anonfun$apply$2.apply(routes_routing.scala:109)
        at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183)
        at play.core.Router$Routes$$anon$1.invocation(Router.scala:377)
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56)
        at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91)
        at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90)
        at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)
        at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: Unable to read categories.xml file
        at net.sf.saxon.regex.charclass.Categories.build(Categories.java:116)
        at net.sf.saxon.regex.charclass.Categories.getCategory(Categories.java:206)
        at net.sf.saxon.regex.charclass.Categories.<clinit>(Categories.java:180)
        ... 97 more
[error] a.a.ActorSystemImpl - Uncaught error from thread [play-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.ExceptionInInitializerError: null
        at net.sf.saxon.regex.RECompiler.escape(RECompiler.java:366) ~[na:na]
        at net.sf.saxon.regex.RECompiler.parseTerminal(RECompiler.java:930) ~[na:na]
        at net.sf.saxon.regex.RECompiler.piece(RECompiler.java:971) ~[na:na]
        at net.sf.saxon.regex.RECompiler.parseBranch(RECompiler.java:1091) ~[na:na]
        at net.sf.saxon.regex.RECompiler.parseExpr(RECompiler.java:1141) ~[na:na]
        at net.sf.saxon.regex.RECompiler.compile(RECompiler.java:1273) ~[na:na]
Caused by: java.lang.RuntimeException: Unable to read categories.xml file
        at net.sf.saxon.regex.charclass.Categories.build(Categories.java:116) ~[na:na]
        at net.sf.saxon.regex.charclass.Categories.getCategory(Categories.java:206) ~[na:na]
        at net.sf.saxon.regex.charclass.Categories.<clinit>(Categories.java:180) ~[na:na]
        at net.sf.saxon.regex.RECompiler.escape(RECompiler.java:366) ~[na:na]
        at net.sf.saxon.regex.RECompiler.parseTerminal(RECompiler.java:930) ~[na:na]
        at net.sf.saxon.regex.RECompiler.piece(RECompiler.java:971) ~[na:na]
```

**Comment by martin-honnen** [comment]
Does "If I type something" really mean any attempt to type code in the XSLT causes that exception or did you get that exception with some particular XSLT?
Saxon had a problem related to that "categories.xml" file in a particular Maven build, see https://saxonica.plan.io/issues/3252 but as far as I understand that it is fixed since 9.8.0.2. I am currently not sure why you would run into that problem, unless the Scala/sbt build tool pulls some old Saxon releases from Maven and somehow has them on the class path.

**Comment by adrianmihalko** [comment]
It fails here:

```
<xsl:stylesheet version="2.0" xmlns:g="http://base.google.com/ns/1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output cdata-section-elements="title" indent="yes" omit-xml-declaration="yes"
    />
    <xsl:strip-space elements="*"/>
    

    <!-- rename nodes  -->

    <xsl:template match="title" >
        <xsl:copy>
            <xsl:value-of select="normalize-space( replace(replace(replace(replace(replace(.,'NEW',''),'^.\d+ MIEZ ',''),'((Banana 90|Banana 70|Banana 50|Banana 30 Grey|Banana 30 Black|Banana 10 Green|Banana 10 Black)\s+)[0-9]+\s+(.*)','$1$3'),' 29',' 29'),' 27.5',' 27.5'))"/>
        </xsl:copy>
    </xsl:template> 
   
</xsl:stylesheet>
```

Doesn't matter if I select Saxon 9.8.x ot 9.7.x

With old XSL-Tester it works.

I don't know if it matters, but I just pointed the config to my old database.

**Comment by martin-honnen** [comment]
I can reproduce that problem here, I will need to find out what Saxon needs that categories file for and why it can't load it with the 9.7 or 9.8 plugins. That might take me a while as Java class loading problems is not something I am used to solve.

**Comment by martin-honnen** [comment]
Here are my findings so far: Saxon keeps some information it needs for regular expression matching in separate XML files and loads them on demand. That categories.xml file mentioned in the error message did not exist in Saxon 9.5 so that is why the code works there in the Saxon 9.5 based old XSL-tester. However, some other information like Unicode blocks were already kept in Saxon 9.5 in XML files like unicodeBlocks.xml and when trying to use them, as in http://xsltransform.hikmatu.com/948Fn5e where I use `replace(., '\p{IsLatinExtended-A}', '')`, the old XSL-tester also runs into an error and does not manage to run the XSLT code. So basically the mechanism to load the files does not work in the architecture used by the XSL-tester. The class and file loading seems to be implemented in https://github.com/martin-honnen/XSLT-Tester/blob/master/app/net/xsltransform/plugin/JarClassLoader.java, I will need to see whether I can understand that code and find ways to fix it so that Saxon manages to load its files.

**Comment by martin-honnen** [comment]
It seems that the used JarClassLoader https://github.com/martin-honnen/XSLT-Tester/blob/master/app/net/xsltransform/plugin/JarClassLoader.java pulls in all `.class` files in the loaded `.jar` file into byte arrays, if I interpret https://stackoverflow.com/questions/20835964/how-to-get-the-url-to-an-embedded-resource-in-play-dist/ correctly then this was done to allow various versions of libraries (I assume of Saxon) to be used in the same Play application. The current `JarClassLoader` does not do the same (i.e. load them into byte arrays in memory) for the `.xml` files in the `.jar` and therefore Saxon, when trying to load these files, simply gives an exception. I am wondering now whether a good way to fix it is really to consume more memory and also read the various XML files into memory. I wonder whether it is not a better and cleaner fix to avoid the whole approach and revert to simply support one Saxon 9 version. @adrianmihalko, as you are the only one asking for an updated Java version of XSL-tester, can you live with a version that simply supports the latest Saxon 9.8 HE (which is an XSLT 3 processor but supports backwards compatibility to XSLT 1 and 2 so you could run them with that Saxon version as well)?

**Comment by adrianmihalko** [comment]
Of course I can. I don't switch between versions in XSLT tester, but because I have some XSLT3 it would be nice to run them locally with the new version Saxon 9.8 HE.

**Comment by martin-honnen** [comment]
@adrianmihalko, I have pushed various changes to the Java and Scala files that restrict the application to use only one Saxon 9 version, namely Saxon 9.8 HE. Please test whether that works for you and report back whether you have run into any problems. If there are no problems I might clean up the whole stuff by removing comment out code and by removing Saxon 9.7 completely but that is than more cosmetical than being important to fix the previous problems with the regular expression Unicode problems.

**Comment by adrianmihalko** [comment]
@martin-honnen perfectly works now. Thanks for your help.

**Comment by adrianmihalko** [comment]
@martin-honnen 

Is there any way to enable file system functions?

```
Static error at char 10 in {fs:exists(fs:new($filename))} in expression in xsl:if/@test on line 19 column 53 
  XPST0017: Cannot find a 1-argument function named {java.io.File}new(). External function
  calls have been disabled
```

**Comment by martin-honnen** [comment]
Saxon 9 HE doesn't support calling into Java with reflexive code so accessing `java.io.File` has never worked  I think. Additionally as this was supposed to be hosted publically the code in https://github.com/martin-honnen/XSLT-Tester/blob/master/app/net/xsltransform/plugin/Saxon9HEPlugin.java#L40 sets `transformerFactory.setAttribute("http://saxon.sf.net/feature/allow-external-functions", "off");`, you could try changing that to `transformerFactory.setAttribute("http://saxon.sf.net/feature/allow-external-functions", "on");` if you are in a closed, controlled environment and then some restrictions (http://saxonica.com/html/documentation/configuration/config-features.html) are lifted. You might be able to use `doc-available` or `unparsed-text-available` if you want to check XML or text files, as far as I remember that is not blocked by the settings.
